use fixed alias for cloudfront domain
giantswarm/capa-iam-operator pull request #178
Opened 2023-06-19 07:10 UTC by bdehri

2023-07-04 08:08 UTC, fiunchinho reviewed
I left some comments and suggestions. Let me know if you have any questions or want to talk about it.

2023-07-04 08:08 UTC, fiunchinho commented on controllers/awscluster_controller.go
> +			return ctrl.Result{}, err
Using this function, we can get the stack trace when an error is returned, making it easier to know where the error happened
```
errors.WithStack(err)
```

2023-07-04 08:08 UTC, fiunchinho commented on controllers/awscluster_controller.go
> +			MainRoleName:              "-",
I see that the `MainRoleName` is `-`. Is this expected?

2023-07-04 08:08 UTC, fiunchinho commented on controllers/awscluster_controller.go
> +			logger.Error(err, "failed to remove finalizer on awsCluster")
```suggestion
			logger.Error(err, "failed to remove finalizer from awsCluster")
```

2023-07-04 08:08 UTC, fiunchinho commented on controllers/awscluster_controller.go
> +	Scheme                    *runtime.Scheme
I think you don't need this field and it could be removed.

2023-07-04 08:09 UTC, fiunchinho commented
Please, add an entry to the changelog explaining the changes.

2023-07-06 14:11 UTC, fiunchinho approved these changes

2023-07-06 14:12 UTC, fiunchinho commented on controllers/awscluster_controller.go
> +	EnableIRSARole            bool
I don't think this is used anymore.

2023-07-06 14:12 UTC, fiunchinho commented on controllers/awscluster_controller.go
> +			return ctrl.Result{}, err
```suggestion
			return ctrl.Result{}, errors.WithStack(err)
```

2023-07-06 14:14 UTC, fiunchinho commented on controllers/awsmachinetemplate_controller.go
>  			return ctrl.Result{}, err
```suggestion
			return ctrl.Result{}, errors.WithStack(err)
```

2023-07-06 14:14 UTC, fiunchinho requested changes
We could use `errors.WithStack(err)` in many more places to help debugging when something goes wrong.

2023-07-10 06:54 UTC, bdehri commented
> We could use `errors.WithStack(err)` in many more places to help debugging when something goes wrong.

Every return statement from a reconciler should return error with stack now.

2023-07-10 08:32 UTC, merged